import math
from graphviz import Digraph

# Value is none other that a classical implementation of a graph
# when a Value out is generated by an op of other Values, those are stored as Value children in _prev
# used for calculating the topilogical sorted list of values needed for the backward pass
# and out.grad is also stored in the backward pass function of both the Value that generated it
# it will be called during backward pass

class Value:

    def __init__(self, data, _children=(), _op='', label=''):
        self.data = data
        self.grad = 0 
        # it's the function which we need to apply to the prev Value
        # default is None (e.g. lead nodes doens't need to be backprop)
        self._backward = lambda: None
        self._prev = set(_children)
        self._op = _op
        self.label = label

    
    def __repr__(self):
        return f"Value(data={self.data})"
    
    def __add__(self, other):
        # that's the trick, when I create a new val, let's say o = n+b
        # n associate o with its out, and stores _backward as the pass needed in case of +
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data+other.data, (self, other), '+')

        def _backward():
            # as we said before, the grad of current val is just the grad of val calculated after it in case of +
            self.grad += 1.0 * out.grad
            other.grad += 1.0 * out.grad
        out._backward = _backward
        return out
    
    def __radd__(self, other):
        return self + other
    
    def __mul__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data*other.data, (self, other), '*')
        def _backward():
            # as we said before, the grad of current val is the grad of val calculated after it * the other val in case of *
            self.grad += other.data * out.grad
            other.grad += self.data * out.grad
        out._backward = _backward
        return out
    
    def __pow__(self, other): #to implement division
        assert isinstance(other, (int,float)) #pow supports int/float for now
        out = Value(self.data**other, (self,), f'**{other}') # only self in _prev, since the other is not a Value

        def _backward():
            self.grad += other * (self.data ** (other-1)) * out.grad #d(x**n) = n*x**(n-1)
        out._backward = _backward
        return out

    
    def __rmul__(self, other):
        return self*other
    
    # all new methods to implement basic num ops
    def __truediv__(self, other):
        return self * (other**-1)
    
    def __neg__(self):
        return self * -1
    
    def __sub__(self, other):
        return self + (-other)
    
    # used tanh for explanatory purposes, but we cooul potentially build any f tipycally used
    def tanh(self):
        n = self.data
        t = (math.exp(2*n)-1)/(math.exp(2*n)+1)
        out = Value(t, (self, ), 'tanh')
        def _backward():
            # as we said before, the grad tanh = 1 - o**2, ofc multuplied by next val grad (if any)
            self.grad += (1 - t**2) * out.grad
        out._backward = _backward
        return out
    
    def exp(self):
        n = self.data
        out = Value(math.exp(n), (self, ), 'exp')
        def _backward():
            self.grad += out.data * out.grad #out.data is exp(n) which is the derivative of exp(n)
        out._backward = _backward
        return out
    
    def backward(self):
        topo = []
        visited = set()
        def build_topo(v):
            if v not in visited:
                visited.add(v)
                for child in v._prev:
                    build_topo(child)
                topo.append(v)
        build_topo(self)

        self.grad=1.0 #default to consider base case of the right most value
        for node in reversed(topo):
            node._backward()


def trace(root):
    # we backward navigate a tree, which is what we build with Value class
    nodes, edges = set(), set()
    def build(v):
        if v not in nodes:
            nodes.add(v)
            for child in v._prev:
                edges.add((child, v))
                build(child)
    build(root)
    return nodes, edges

def draw_dot(root, format='svg', rankdir='LR'):
    """
    format: png | svg | ...
    rankdir: TB (top to bottom graph) | LR (left to right)
    """
    assert rankdir in ['LR', 'TB']
    nodes, edges = trace(root)
    dot = Digraph(format=format, graph_attr={'rankdir': rankdir}) #, node_attr={'rankdir': 'TB'})
    
    for n in nodes:
        dot.node(name=str(id(n)), label = "{ %s | data %.4f | grad %.4f }" % (n.label, n.data, n.grad), shape='record')
        if n._op:
            dot.node(name=str(id(n)) + n._op, label=n._op)
            dot.edge(str(id(n)) + n._op, str(id(n)))
    
    for n1, n2 in edges:
        dot.edge(str(id(n1)), str(id(n2)) + n2._op)
    
    return dot
